### ISSUE TITLE
MAJOR ISSUE (I'm assuming)

### ISSUE THREAD

**Issue by MrTailson** [a-soulspark/TeaKettle#1]
**Describe the bug**
When crafting with the shears and a rose plant to create rose petals, it uses up the shears entirely rather than reducing the tool's durability.

**To Reproduce**
1. Place shears and a rose bush into a crafting grid either in the player inventory or on a crafting table.
2. Craft rose petals and click on the item to place into your inventory.
3. The shears are now gone and used up.

**Expected behavior**
I would have expected the shears to be slightly used when crafting the rose petals.

**Screenshots**

**Additional context**
Version: tea_kettle-0.1

**Comment by a-soulspark** [comment]
yup, that's totally not supposed to happen. thanks for the report!
unfortunately, I can't offer refunds for your lost shears though. sorry about that :p

**Comment by MrTailson** [comment]
> yup, that's totally not supposed to happen. thanks for the report!
> unfortunately, I can't offer refunds for your lost shears though. sorry about that :p

Thank you for the consideration. I patiently await.

**Comment by a-soulspark** [comment]
v0.1.1 should've fixed the bug. whew.
