### ISSUE TITLE
Endergetic Expansion compatibility request.

### ISSUE THREAD

**Issue by Moofellow** [a-soulspark/TeaKettle#10]
**Description**
When a Kettle is placed on an Ender Campfire (endergetic:ender_campfire), it could remain an Ender Campfire rather than turning into a Soul Campfire.

Sorry for all the issue reports and feature requests, by the way.

**Comment by a-soulspark** [comment]
wait... it does? I didn't expect that to happen, but now that you mentioned it makes sense why

thanks for all the reports you've made, they really helped me learn and improve the mod ^^

**Comment by Moofellow** [comment]
You're welcome! :D

**Comment by a-soulspark** [comment]
Ok, it should now be compatible with Endergetic's campfire, and when Abnormals' Caverns and Chasms gets released, I'll add support for it as well. phew!
