### ISSUE TITLE
Crashes while using item

### ISSUE THREAD

**Issue by SAGESSE-CN** [a-soulspark/TeaKettle#11]
**Describe the bug**
Crashes while using item

**Additional context**
tea_kettle-1.16.4-0.3.2.0
https://pastebin.com/yRMbYXFy

**Comment by a-soulspark** [comment]
ono, a crash
could you give a bit more context on the crash? I really don't know how to reproduce it.
what item were you using? was there anything in the cup?

**Comment by SAGESSE-CN** [comment]
In a single player, put down a teacup and some rose petals then right-click on the boiled tea kettle

**Comment by SAGESSE-CN** [comment]
it is normal in multiplayer players, I kind of don't understand, but I looked at the code this is really a possible bug

https://github.com/a-soulspark/TeaKettle/blob/f5b703fef62fd5aa26a0b0ad67028ec5135af2e8/src/main/java/soulspark/tea_kettle/common/recipes/TeaSteepingRecipe.java#L41

**Comment by a-soulspark** [comment]
well this is weird, IDEA says an item stack can never be null, so that line shouldn't be causing any trouble. still, I'll try reproducing it with the steps you gave me, and see if I can fix it. thanks!
