### ISSUE TITLE
Farmer's Delight compability

### ISSUE THREAD

**Issue by FoodSeeker** [a-soulspark/TeaKettle#12]
Can we please heat up kettles on stoves from Farmer's Delight?
The art of it is realy nice and I'd love to have that combined with that cute kettle.

**Comment by a-soulspark** [comment]
I totally agree, and in fact it's supposed to work already, as someone has already requested it! what version of Farmer's Delight have you tried it on, and it didn't work?

**Comment by FoodSeeker** [comment]
Oh dang it, I will look like a fool now. It's working, I was just looking at the wrong kettle XD
