### ISSUE TITLE
[Mod Compatibility] Biomes O' Plenty Lavender Tea

### ISSUE THREAD

**Issue by Lucky-Red** [a-soulspark/TeaKettle#14]
**Mod name**
Biomes O' Plenty

**Features to add compatibility with**
Lavender tea made from the lavender added by Biomes O' Plenty.

**Comment by a-soulspark** [comment]
ok, so Biomes O' Plenty doesn't add tea, but it adds lavender. I finally understand '>.>
sure, if you have Abundance and Biomes O' Plenty installed, it makes sense to brew Lavender Tea with it. I'll do that 👍
