### ISSUE TITLE
[Mod Compatibility] Fireweed Tea from Simply Tea's integration with Terra Incognita

### ISSUE THREAD

**Issue by Lucky-Red** [a-soulspark/TeaKettle#15]
**Mod name**
Simply Tea/Terra Incognita

**Features to add compatibility with**
Simply Tea has built-in compatibility with Terra Incognita, adding a tea that can be made from the Fireweed plant from that mod. Unlike the other teas added by Simply Tea, the Fireweed tea isn't currently compatible with the kettle/cup filling mechanic added by Tea Kettle.

**Comment by a-soulspark** [comment]
hadn't heard of this mod till now. I'll make sure to add this 👍
