### ISSUE TITLE
Simply Tea Cinnamon Hot Chocolate

### ISSUE THREAD

**Issue by Lucky-Red** [a-soulspark/TeaKettle#16]
**Describe the bug**
The Hot Chocolate from Simply Tea can have a Tea Stick from that mod added to it, turning it into a Cup of Hot Chocolate *with Cinnamon*. Placing this cup into the world as a block and picking it back up gives the player a cup of regular hot chocolate.

**To Reproduce**
1. Craft a "Cup of Hot Chocolate" from Simply Tea
2. Craft the Hot Chocolate with a Tea Stick to get a "Cup of Hot Chocolate *with Cinnamon*"
3. Place the cup
4. Pick the cup back up to receive a regular "Cup of Hot Chocolate"

**Comment by a-soulspark** [comment]
that's a new feature added with a recent Simply Tea update. I'll update Tea Kettle to keep it up-to-date with this Simply Tea update.
thanks for reporting this 👍
