### ISSUE TITLE
Kettles should accept water, not all fluids!

### ISSUE THREAD

**Issue by COLDW0LF** [a-soulspark/TeaKettle#17]
Hi there, love the mod... it's amazing to finally have a kettle in my kitchen!

I've noticed that the kettle accepts basically any fluid for filling.
While it's certainly convenient, it's also a little odd... Immersive Engineering's creosote can be used for making tea!

My suggestion/request would be to prevent this from happening, if possible.
Perhaps Forge tags could dictate which fluids are acceptable, so that they could be customised?

**Comment by a-soulspark** [comment]
oops, that doesn't sound like it should happen! thanks for reporting that bug 👍

I'll see if I can implement a tag for that, thanks.
