### ISSUE TITLE
Client crash when using an empty kettle on a Supplementaries Water Jar

### ISSUE THREAD

**Issue by Carloslionheart** [a-soulspark/TeaKettle#18]
**Describe the bug**
Client crashes when a player right clicks a water jar with an empty kettle.

**To Reproduce**
Version of Supplementaries: 0.14.4f

Grab an empty kettle, and right click a jar with water in it. Client crashes instantly.

**Expected behavior**
The empty kettle should be filled when a water jar is right clicked.

**Additional context**
This behavior used to work on Supplementaries 0.14.2. I originally reported this issue on the Supplementaries github [here](https://github.com/MehVahdJukaar/Supplementaries/issues/84).

**Comment by MehVahdJukaar** [comment]
I've added tea kettle container to the water fluid itself (one can now do this using the new library pretty easily), so it works with all of my fluid holders (will be out next lib update). I think you can just remove that code and it should all be handle by mine :)
