### ISSUE TITLE
Unable to give blocks "tea_kettle:hot" block tag through CraftTweaker

### ISSUE THREAD

**Issue by Carloslionheart** [a-soulspark/TeaKettle#2]
**Describe the bug**
Attempting to give, for example, "minecraft:stone" the "tea_kettle:hot" block tag is not working through CraftTweaker. It seems it might be involved with the mod id itself: "tea_kettle". When this is changed, the block is successfully tagged.

**Expected behavior**
Being able to tag blocks with the "tea_kettle:hot" block tag through CraftTweaker

The following is a sample script:
[tagStone.zs](https://gist.github.com/Carloslionheart/26caa6c25f1a097e5c50fe309a940853
)

**Additional context**
I'm unsure if this is an issue from CT, or if it is a conflict between CT and this mod.

**Comment by a-soulspark** [comment]
Hmm, your script works fine for me when using CraftTweaker-1.16.5-7.1.0.151 and Forge 35.1.4.
it prob isn't an issue with Tea Kettle.

**Comment by Carloslionheart** [comment]
Thank you for responding!

So I have tried using this script in the version of CraftTweaker and Forge you specified, but the blocks still don't have that tag. I decided to update to a future version of Forge (36.0.58) to see if it would fix it, yet the issue remains. I also checked the crafttweaker.log file, and it seems the tag is added with no issues, however when checking in game with the F3 screen the block is untagged.

Im attaching the crafttweaker.log file here:

[crafttweaker.log](https://github.com/a-soulspark/TeaKettle/files/6138254/crafttweaker.log)

For context, I'm running on Windows 10.

Any ideas?

**Comment by a-soulspark** [comment]
This is really weird.
I managed to reproduce the issue by creating a fresh instance of Minecraft with a new .minecraft folder. I'm able to add tags through a datapack in the world, just not through CraftTweaker, though in the logs, it still thinks the tag contains `minecraft:stone`. I'll try asking in the CraftTweaker Discord to see if anyone can figure this out.
For the time being, you can check [this mod](https://www.curseforge.com/minecraft/mc-mods/drp-global-datapack) out. It lets you add a global datapack to a modpack, and with that, you can properly add values to the tag with a datapack [like the one I used while testing](https://github.com/a-soulspark/TeaKettle/files/6143031/example.zip).

**Comment by Carloslionheart** [comment]
Perfect, Thank you for all the help!
