### ISSUE TITLE
The resurrection of Issue #4

### ISSUE THREAD

**Issue by Moofellow** [a-soulspark/TeaKettle#20]
**Description**
Lavender from Abundance can be placed into the cup, but interacting on the full cup with a Boiling Kettle does nothing.
Sorry, whoever wrote Issue #4.

**To Reproduce**
1. put some lavender in a gotdamn cup
2. try to fill the cup with boiling water
3. cry just a little bit :(

**Expected behavior**
Lavender Tea should be created when boiling water is poured into a cup with Lavender in it.
Also, for the cross-mod compatibility gods to maybe not hate us quite as much.

**Screenshots**
![image](https://user-images.githubusercontent.com/72464266/131205621-6d5b88ce-ac8d-4cd2-aea3-d945258dcf83.png)
![image](https://user-images.githubusercontent.com/72464266/131205628-fd33ab9f-4616-42dc-91d5-1e1713f55ace.png)

sorry about the lack of details and uncharacteristic written tone, it's starting to get late

**Comment by a-soulspark** [comment]
oops, that's not how you make lavender tea! you forgot to add leaves (any kind will work), it's the same as in the original mod ^v^ 
when in doubt, check the JEI recipes, they're very well detailed (I hope)

**Comment by Moofellow** [comment]
well crap, sorry about that lolw
