### ISSUE TITLE
[Cross-mod compatibility] Refilling tea kettle with water using sink from Cooking for Blockheads

### ISSUE THREAD

**Issue by AbacusOperator** [a-soulspark/TeaKettle#3]
**Describe your feature here**
Please add ability to fill tea kettle with water using sink from Cooking for Blockheads (cookingforblockheads:sink). Sink is an infinite water source block, from which water can be extracted with bucket, bottle or pumping.

**Comment by a-soulspark** [comment]
alright, I'll see if I can add support to any liquid containers, including the sink. thanks for the suggestion!
