### ISSUE TITLE
Mod compat with Abundance

### ISSUE THREAD

**Issue by erisdev** [a-soulspark/TeaKettle#4]
Abundance adds lavender and its own lavender tea item that grants 10 seconds of _Supportive_, an effect added by that mod that buffs entites close to the player. It would be cool if, when Abundance is installed, you could brew that tea in a tea cup so that it could be enhanced like the other herbal teas.

**Comment by a-soulspark** [comment]
sure, I'll see if I can do that!
I'm still trying to figure out compatibility with other mods' teas, once I do I'll add support for Simply Tea and Abundance too.

**Comment by erisdev** [comment]
Awesome, thank you!
