### ISSUE TITLE
Bamboo Tea can be crafted with a crafting table.

### ISSUE THREAD

**Issue by Moofellow** [a-soulspark/TeaKettle#7]
**Description**
Cup of Bamboo Tea can be crafted with a Bamboo Leaf in a crafting table.

**To Reproduce**
Open the crafting table.
Put a Bamboo Leaf in the crafting table.
Get a Cup of Bamboo Tea.

**Expected**
Boil some water in a Kettle.
Place a Bamboo Leaf in a Cup.
Pour the water into the Cup.
Get a Cup of Bamboo Tea.

**Screenshot**
![bamboo_tea_bug](https://user-images.githubusercontent.com/72464266/115974405-2a2d1200-a522-11eb-86dc-f27b31573409.png)

**Comment by a-soulspark** [comment]
oops, a little debug code slipped by. thanks for pointing it out!
