### ISSUE TITLE
Soul Campfire kettle bug.

### ISSUE THREAD

**Issue by Moofellow** [a-soulspark/TeaKettle#9]
**Describe the bug**
Soul Campfires will become Campfires when a kettle is removed from it.

**To Reproduce**
1. Place a filled kettle (fluid doesn't matter) on a Soul Campfire.
2. Take it off at any point.
3. The Soul Campfire will become a Campfire.

**Expected behavior**
1. Place a filled kettle (fluid doesn't matter) on a Soul Campfire.
2. Take it off at any point.
3. The Soul Campfire will remain a Soul Campfire.

**Screenshots**
![experiment1](https://user-images.githubusercontent.com/72464266/116638794-a366a380-a92c-11eb-8fef-8a9bc797f5d4.png)
![experiment2](https://user-images.githubusercontent.com/72464266/116638799-a6619400-a92c-11eb-8266-43652af2080a.png)
![experiment3](https://user-images.githubusercontent.com/72464266/116638802-a8c3ee00-a92c-11eb-923d-5abdadad0e5c.png)

**Comment by a-soulspark** [comment]
thanks for the well-made report! seems to be caused by the CampfireKettleBlock class being generic for both campfires. will push a new patch to fix that
